# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UTube Download

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  issues:
    types: [opened]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Try my utube-issue-parser
      id: parser
      uses: foresightyj/utube-issue-parser@main
      with:                                     
        github-token: ${{secrets.GITHUB_TOKEN}} 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install youtube-dl
      run: sudo -H pip install --upgrade youtube-dl

    - name: Download
      run: youtube-dl -o "./downloads/%(title)s-%(id)s.%(ext)s" -f 'best' ${{steps.parser.outputs.url}}

    # - name: Upload
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: my-artifact
    #     path: ./downloads/

    - name: Upload to youku
      run: |
        sudo -H pip install requests
        sudo -H pip install oss2

    # - name: setup aliyun oss
    #   uses: manyuanrong/setup-ossutil@v1.0
    #   with:
    #     endpoint: oss-cn-qingdao.aliyuncs.com
    #     access-key-id: ${{ secrets.OSS_KEY_ID }}
    #     access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

    # - name: upload to oss
    #   run: ossutil cp -r ./downloads/ oss://utube-download/downloads --update

