# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UTube Download

on:
  issues:
    types: [opened]

jobs:
  download:
    if: ${{ contains(github.event.issue.title, 'http') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: parse issue comments
      id: parser
      uses: foresightyj/actions-parse-issue-body-as@master
      
    - name: remove this issue conditionally 
      uses: vtcaregorodtcev/delete-issue@main
      if: ${{ !contains(github.event.issue.title, 'http') }}
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        issue_node_id: ${{ github.event.issue.node_id }}
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install youtube-dl
      run: sudo -H pip install youtube-dl

    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: oss-cn-qingdao.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

    - name: Download Single
      if: ${{ !contains(github.event.issue.title, 'playlist?list') }}
      run: |
        youtube-dl -o "./downloads/%(title)s-%(id)s.%(ext)s" -f 'best' ${{steps.parser.outputs.text}}
        ossutil cp -r ./downloads/ oss://utube-download/downloads --update

    - name: Download Youtube Playlist
      if: ${{ contains(github.event.issue.title, 'playlist?list') }}
      run: |
        youtube-dl --get-id ${{steps.parser.outputs.text}} | xargs -I '{}' -P 10 youtube-dl  -o "./downloads/%(title)s-%(id)s.%(ext)s" -f 'best' 'https://youtube.com/watch?v={}'
        ossutil cp -r ./downloads/ oss://utube-download/downloads --update




