# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UTube Download

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install youtube-dl
      run: sudo -H pip install --upgrade youtube-dl

    - name: Download
      run: youtube-dl -o "./downloads/%(title)s-%(id)s.%(ext)s" -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' https://www.youtube.com/watch?v=St5B7hnMLjg&list=PL4cUxeGkcC9iEwigam3gTjU_7IA3W2WZA

    # - name: Upload
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: my-artifact
    #     path: ./downloads/
    
    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@v1.0
      with:
        endpoint: oss-cn-qingdao.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

    - name: upload to oss
      run: ossutil cp -r ./downloads/ oss://utube-download/downloads --update

