# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UTube Download

on:
  issues:
    types: [opened]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Add mask
      run: |
          echo "::add-mask::${{ secrets.URL_MASK_1 }}" 

    - uses: actions/checkout@v2

    - name: parse issue comments
      id: parser
      uses: foresightyj/actions-parse-issue-body-as@master
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install youtube-dl
      run: sudo -H pip install --upgrade youtube-dl

    - name: Download
      run: youtube-dl -o "./downloads/%(title)s-%(id)s.%(ext)s" -f 'best' ${{steps.parser.outputs.text}}

    - name: Install requests & oss2
      run: |
        sudo -H pip install requests
        sudo -H pip install oss2

    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: oss-cn-qingdao.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

    - name: upload to oss
      run: ossutil cp -r ./downloads/ oss://utube-download/downloads --update

